name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - uses: actions/checkout@v5

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: server/package-lock.json

    - name: Install dependencies
      working-directory: server
      run: npm install

    - name: Remove pushed .env file
      working-directory: server
      run: rm -f .env

    - name: Stop existing PM2 process if it exists
      run: pm2 delete hlynk-server || true

    - name: Start PM2 process
      working-directory: server
      run: |
        source /etc/profile
        pm2 start index.js --name hlynk-server --interpreter node --update-env

    - name: Save PM2 process list
      run: pm2 save






# # This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# name: Node.js CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:

#     runs-on: self-hosted

#     strategy:
#       matrix:
#         node-version: [24.x]

#     steps:
#     - uses: actions/checkout@v5

#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v5
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#         cache-dependency-path: server/package-lock.json

#     - name: Install dependencies
#       working-directory: server
#       run: npm install

#       # kill pm2 process if it exists to prevent issues with old processes running during deployment
#     - name: Kill existing PM2 process if it exists
#       run: pm2 kill || true

#       # remove .env file if it exists to prevent accidental overwriting of production environment variables
#     - name: Remove .env file if it exists
#       working-directory: server
#       run: rm -f .env

#       # navigate the a specific directory "/var/www/html/hlynk/actions-runner/hlynk/hlynk-api/hlynk-api/server" and run the command "pm2 start index.js --name hlynk-server --interpreter node --update-env" to start or restart the app with PM2, ensuring that the environment variables are updated from the .env file
#     - name: Start or restart PM2 process
#       working-directory: server
#       run: pm2 start index.js --name hlynk-server --interpreter node --update-env

#        # save the PM2 process list to ensure it is restarted on server reboot

#     - name: Save PM2 process list
#       run: pm2 save
